require:
 - rubocop-rails
 - rubocop-rspec
 - rubocop-performance
inherit_from:
  - https://raw.githubusercontent.com/insales/code_style/master/ruby/rubocop.yml
  - https://raw.githubusercontent.com/insales/code_style/master/ruby/rubocop_rails.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
